package com.gulfcam.fuelcoupon.user.entity;

public enum ETypeAccount {
	STORE_KEEPER,
	MANAGER_COUPON,
	MANAGER_SPACES_2,
	COMPTABLE,
	DSI_AUDIT,
	MANAGER_SPACES_1,
	COMMERCIAL_ATTACHE,
	SALES_MANAGER,
	MANAGER_STORE,
	MANAGER_ORDER,
	TREASURY,
	CUSTOMER_SERVICE,
	MANAGER_STATION,
	POMPIST
}
