package com.gulfcam.fuelcoupon.user.entity;

public enum ETypeAccount {
<<<<<<< HEAD
<<<<<<< HEAD
	STORE_KEEPER,
	MANAGER_COUPON,
	MANAGER_SPACES_2,
	COMPTABLE,
	DSI_AUDIT,
	MANAGER_SPACES_1,
	COMMERCIAL_ATTACHE,
	SALES_MANAGER,
	MANAGER_STORE,
	MANAGER_ORDER,
	TREASURY,
	CUSTOMER_SERVICE,
	MANAGER_STATION,
	POMPIST
=======
	STORE_KEEPER, MANAGER_COUPON, MANAGER_SPACES_2, COMPTABLE, DSI_AUDIT, MANAGER_SPACES_1, COMMERCIAL_ATTACHE, SALES_MANAGER, MANAGER_STORE, MANAGER_ORDER, TREASURY, CUSTOMER_SERVICE, MANAGER_STATION, POMPIST
>>>>>>> 0e0546e1a1696567d3c70419c5fcf4c1501b95d6
=======
	STORE_KEEPER, MANAGER_COUPON, MANAGER_SPACES_2, COMPTABLE, DSI_AUDIT, MANAGER_SPACES_1, COMMERCIAL_ATTACHE, SALES_MANAGER, MANAGER_STORE, MANAGER_ORDER, TREASURY, CUSTOMER_SERVICE, MANAGER_STATION, POMPIST
>>>>>>> 0e0546e1a1696567d3c70419c5fcf4c1501b95d6
}
