package com.gulfcam.fuelcoupon.utilities.entity;

public enum ESettingPropertie {
    SUBSCRIPTION,PAYMENT,APPLICATIONTOOFFERJOB,VALIDATIONPROFILMEMBER,NOTIFICATIONTESTLANGUAGEFINISH,TECHNIQUESUPPORT,SUSCRIPTIONSUPPORT,OFFERJOBSUPPORT,EVALUATIONSUPPORT,FORMATIONSUPPORT,RECRUITERPROCESSUSSUPPORT,OTHER
}
