package com.gulfcam.fuelcoupon.utilities.entity;

public enum EStatus {
	STORE_ENABLE, CREATED, CANCELED, ACCEPTED, CLOSED, DELETED, IN_PROCESS_OF_DELIVERY, DELIVERED, ACTIVATED, DISABLED, SUSPENDED, AVAILABLE
}
